### ISSUE TITLE
Buggy lua if statement

### ISSUE THREAD

**Issue by mayanksuman** [wincent/pinnacle#5]
I was having a look at your code for porting my init.vim to init.lua. However, I have found a bug regarding coding in all if or other conditional statement.

In `lua` only  nil and false evaluate to false (0 or empty string is not false). Conditions, like [this](https://github.com/wincent/wincent/blob/4326c6580eb9bed4eccf1c07088f17e033069ad5/aspects/vim/files/.vim/lua/wincent/pinnacle.lua#L5), will always return true even if the feature (i.e. gui is not running) is not there.

You can check the condition in vim by issuing `:lua print(vim.fn.has('gui') and true or false)` and you will never get a false even if vim is running in a terminal. The right conditional is `vim.fn.has('gui') == 1`.

**Comment by wincent** [comment]
Ah, actually this was already fixed in 545892dc12d3d94f0335b0bbdfc80bfc85efd828.
